language: c
dist: xenial
sudo: required

matrix:
  include:
    - name: Linux (gcc)
      os: linux
      compiler: gcc
    - name: Linux (clang)
      os: linux
      compiler: clang
    - name: macOS (Xcode)
      os: osx

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install --yes cmake
    fi

script:
  - cmake .
  - make all
  - make check
