language: c
dist: trusty
sudo: required

matrix:
  include:
    - name: Linux (gcc)
      os: linux
      compiler: gcc
    - name: Linux (clang)
      os: linux
      compiler: clang-6.0
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-6.0', 'ubuntu-toolchain-r-test']
          packages: ['g++-4.9','clang-6.0']
    - name: macOS (Xcode)
      os: osx

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install --yes cmake
    fi

script:
  - cmake .
  - make all
  - make check
