language: c
dist: xenial
sudo: required

matrix:
  include:
    - name: Linux (gcc-8)
      os: linux
      compiler: gcc-8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-8']
    - name: Linux (clang)
      os: linux
      compiler: clang
    - name: macOS (Xcode)
      os: osx

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install --yes cmake
    fi

script:
  - cmake .
  - make all
  - make check
